name: ${project.name}
version: ${project.version}
author: DSH105
description: The Next Generation Of Particle Effect Control
website: ${project.url}
main: ${main.class}
commands:
    stupdate:
        description: Update the plugin.
    sparktrail:
        description: View plugin information